version: "3"

services:
  es:
    build: 
      context: ./es
      dockerfile: Dockerfile 
      args: 
        SLACK_ALERT_P1: ${SLACK_ALERT_P1}
        SLACK_ALERT_P2: ${SLACK_ALERT_P2}
    image: "elasticsearch:${TAG}"
    container_name: es
    volumes:
      - ./configs/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:rw
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.0
    container_name: kibana
    ports:
      - 5601:5601
    links:
      - es:elasticsearch
    depends_on:
      - es

  heartbeat:
    image: docker.elastic.co/beats/heartbeat:7.6.0
    container_name: heartbeat
    links:
      - es:elasticsearch
      - kibana:kibana
    environment:
      - ELASTIC_SEARCH_HOSTS=[${ELASTIC_SEARCH_HOSTS}]
      - KIBANA_HOST=${KIBANA_HOST}
      - DEBUG_LEVEL=${DEBUG_LEVEL}
      - P1_URLS=${P1_URLS}
      - P2_URLS=${P2_URLS}
    volumes:
      - ./configs/heartbeat.yml:/usr/share/heartbeat/heartbeat.yml:ro
      - ./configs/monitors.d:/usr/share/heartbeat/monitors.d:ro
    command:
      - --strict.perms=false
    restart: on-failure
    depends_on:
      - es
      - kibana
