version: "3"

services:
  es:
    build:
      context: ./
      dockerfile: es/Dockerfile
    image: "elasticsearch:${TAG}"
    container_name: elasticsearch
    hostname: elasticsearch
    networks:
      - heartbeat
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - DISCOVERY_TYPE=${DISCOVERY_TYPE}
      - SLACK_ALERT_P1=${SLACK_ALERT_P1}
      - SLACK_ALERT_P2=${SLACK_ALERT_P2}
      - PAGERDUTY_KEY=${PAGERDUTY_KEY}
      
  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.0
    container_name: kibana
    hostname: kibana
    networks:
      - heartbeat
    ports:
      - 5601:5601
    depends_on:
      - es

  hb:
    build:
      context: ./
      dockerfile: hb/Dockerfile
    image: "heartbeat:${TAG}"

  hb1:
    image: "heartbeat:${TAG}"
    container_name: hb1
    hostname: hb1
    networks:
      - heartbeat
    environment:
      - ELASTIC_SEARCH_HOSTS=[${ELASTIC_SEARCH_HOSTS}]
      - KIBANA_HOST=${KIBANA_HOST}
      - DEBUG_LEVEL=${DEBUG_LEVEL}
      - P1_URLS_STATUS_ONLY=${P1_URLS_STATUS_ONLY}
      - P1_URLS_WITH_BODY_CHECK=${P1_URLS_WITH_BODY_CHECK}
      - P2_URLS_STATUS_ONLY=${P2_URLS_STATUS_ONLY}
      - P2_URLS_WITH_BODY_CHECK=${P2_URLS_WITH_BODY_CHECK}
    command:
      - --strict.perms=false
    restart: on-failure
    depends_on:
      - hb
      - es
      - kibana

  hb2:
    image: "heartbeat:${TAG}"
    container_name: hb2
    hostname: hb2
    networks:
      - heartbeat
    environment:
      - ELASTIC_SEARCH_HOSTS=[${ELASTIC_SEARCH_HOSTS}]
      - KIBANA_HOST=${KIBANA_HOST}
      - DEBUG_LEVEL=${DEBUG_LEVEL}
      - P1_URLS_STATUS_ONLY=${P1_URLS_STATUS_ONLY}
      - P1_URLS_WITH_BODY_CHECK=${P1_URLS_WITH_BODY_CHECK}
      - P2_URLS_STATUS_ONLY=${P2_URLS_STATUS_ONLY}
      - P2_URLS_WITH_BODY_CHECK=${P2_URLS_WITH_BODY_CHECK}
    command:
      - --strict.perms=false
    restart: on-failure
    depends_on:
      - hb
      - es
      - kibana

networks:
  heartbeat:
