version: "3"

services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    container_name: es
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.0
    container_name: kibana
    ports:
      - 5601:5601
    links:
      - es:elasticsearch
    depends_on:
      - es

  heartbeat:
    image: docker.elastic.co/beats/heartbeat:7.6.0
    container_name: heartbeat
    links:
      - es:elasticsearch
      - kibana:kibana
    environment:
      - ELASTIC_SEARCH_HOSTS=["elasticsearch:9200"]
      - KIBANA_HOST="kibana:5601"
    volumes:
      - ./heartbeat.docker.yml:/usr/share/heartbeat/heartbeat.yml:ro
    command: --strict.perms=false
    restart: on-failure
    depends_on:
      - es
      - kibana
