output.elasticsearch:
  hosts: "${ELASTIC_SEARCH_HOSTS}"

setup.kibana:
  host: "${KIBANA_HOST}"

heartbeat.monitors:
  - type: http
    schedule: "@every 5s"
    urls:
      - http://elasticsearch:9200
      - http://kibana:5601
      - https://google.com
