- type: http
  name: P1_HTTP_STATUS_ONLY
  schedule: "@every 60s"
  timeout: 30s
  tags: ["alert_p1"]
  urls: "${P1_URLS_STATUS_ONLY}"
  max_redirects: 3
  check:
    request.method: GET

    response:
      status: 200
