- type: http
  name: P2_HTTP_BODY_CHECK
  schedule: "@every 60s"
  timeout: 30s
  tags: ["alert_p2"]
  urls: "${P2_URLS_WITH_BODY_CHECK}"
  max_redirects: 3
  check:
    request.method: GET

    response:
      status: 200
      body: OK
