cluster.name: "docker-cluster"
discovery.type: "${DISCOVERY_TYPE}"
network.host: 0.0.0.0
xpack.watcher.enabled: true
xpack.monitoring.enabled: false
xpack.security.enabled: false
xpack.license.self_generated.type: trial
