output.elasticsearch:
  hosts: "${ELASTIC_SEARCH_HOSTS}"

setup.ilm.enabled: auto
setup.ilm.rollover_alias: "heartbeat"
setup.ilm.pattern: "{now/M{yyyy.MM}}-000001" 


setup.kibana:
  host: "${KIBANA_HOST}"

http:
  enabled: true
  host: 0.0.0.0
  port: 5066
monitoring:
  enabled: true

heartbeat.config.monitors:
  path: /usr/share/heartbeat/monitors.d/*.yml
  reload.enabled: true
  reload.period: 30s
